---
title: "Bootstrap approach for confidence intervals"
output: pdf_document
date: "2024-06-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl) # to read the initial file
library(magrittr) # for pipes
library(tibble) # for add_column
```

Notes from Efron and Tibshirani (1993):
"It is important to note that B = 100 or 200 is not adequate for confidence interval construction, see Chapter 19." (p161)

# Preliminaries

```{r}
# Importing the database with the artificial forest
trees <- read_excel("~/work/Sim_article2024/Data/artificial_forest_round.xls")
```

```{r}
# Functions to produce a local variable
source("~/work/Sim_article2024/Useful_functions/Circle.R")
```

```{r}
### Constant values

# Sample size
n <- 100

# Marginal density: density of the uniform distribution over 1:1000
# Which leads us to the inclusion density function
p <- sum(rep((1/1000)*(1/1000), n))

# Number of bootstrap samples
B <- 500

# Radius to consider for the circle around each sampled point
R <- 5
```

# Creating one sample

```{r}
# Dataframe containing all coordinates of n randomly chosen points
# Uniform sampling over the whole territory
random_points <- data.frame(x = runif(n, 0, 1000), y = runif(n, 0, 1000))
```

# Creating other samples based on the previous one

```{r}
f_boot <- function(df_sample, B){
  # df_sample: original sample; B: number of bootstrap samples made thanks to df_sample
  
  df_boot <- tibble(.rows = nrow(df_sample))
  for (b in 1:B) {
    nb <- sample(1:nrow(df_sample), nrow(df_sample), replace = TRUE)
    sample_b <- df_sample[nb,]
    df_boot <- df_boot %>% add_column(new_col = sample_b)
    colnames(df_boot)[b] <- paste("ech", b, sep = "")
  }
  return(do.call(data.frame, df_boot))
  # Return a data frame with B samples of 2 variables and of size n
}
```

```{r}
# Making of bootstrap samples
df_boot <- f_boot(random_points, B)
```

# Estimations and confidence intervals based on the bootstrap samples

## With one single circle

```{r}
# Estimation of the total number of trees for each bootstrap sample
est_boot <- c()
for (c in 1:B) {
  a <- c()
  for (i in 1:n) {
    a <- append(a, circle_nb(df_boot[i, (2*c)-1], df_boot[i, 2*c], R))
  }
  est_boot <- append(est_boot, sum(a/p))
}
est_boot <- sort(est_boot)
```

```{r}
rm(a, c, i)
```

```{r}
# Confidence interval based on the percentile approach
lim_inf <- est_boot[floor(B*2.5/100)]
lim_sup <- est_boot[B - floor(B*2.5/100)]
cat("Un intervalle de confiance à 95% par la méthode des percentiles est : [", lim_inf, ";", lim_sup, "]" )
```

```{r}
# Target: the initial sample alone
a <- c()
for (i in 1:n) {
  a <- append(a, circle_nb(random_points[i, 1], random_points[i, 2], R))
}

# Estimated total thus obtained from the initial sample
est_init <- sum(a/p)
```

```{r}
rm(a, i)
```

```{r}
# Confidence interval based on the reverse percentile approach
cat("Un intervalle de confiance à 95% par la méthode des reverse percentiles est : \n[", est_init*2 - lim_sup, ";", est_init*2 - lim_inf, "]" )
```

## With three circles

```{r}
### With 3 circles as described in Trinh et alii (2024), page 8

est_boot_3 <- c()
for (c in 1:B) {
  a <- c()
  for (i in 1:n) {
    a <- append(a, circle3_nb(df_boot[i, (2*c)-1], df_boot[i, 2*c], 15, 9, 6))
  }
  est_boot_3 <- append(est_boot_3, sum(a/p))
}

est_boot_3 <- sort(est_boot_3)
```

```{r}
# Confidence interval based on the percentile approach
lim_inf <- est_boot_3[floor(B*2.5/100)]
lim_sup <- est_boot_3[B - floor(B*2.5/100)]
cat("Un intervalle de confiance à 95% par la méthode des percentiles est : [", lim_inf, ";", lim_sup, "]" )
```

```{r}
# Target: the initial sample alone
a <- c()
for (i in 1:n) {
  a <- append(a, circle3_nb(random_points[i, 1], random_points[i, 2], 15, 9, 6))
}

# Estimated total thus obtained from the initial sample
est_init_3 <- sum(a/p)
```

```{r}
# Confidence interval based on the reverse percentile approach
cat("Un intervalle de confiance à 95% par la méthode des reverse percentiles est : \n[", est_init_3*2 - lim_sup, ";", est_init_3*2 - lim_inf, "]" )
```

# BCA and ABC bootstrap CI

```{r}
## WARNING:
## Useless function for now!

# Largely based on the code given in https://gitlab.com/scottkosty/bootstrap/-/blob/master/R/bcanon.R
# Function explained in Efron and Tibshirani (1993)
bcanon <- function(x,bootsam,theta,...,alpha =
                     c(.025,.05,.1,.16,.84,.9,.95,.975)) { 
    if (!all(alpha < 1) || !all(alpha > 0))
      stop("All elements of alpha must be in (0,1)")

    # alpha_sorted <- sort(alpha)
    # if (nboot <= 1/min(alpha_sorted[1],1-alpha_sorted[length(alpha_sorted)]))
    #   warning("nboot is not large enough to estimate your chosen alpha.")

    call <- match.call()
    # n <- length(x)
    n <- nrow(x)
    # thetahat <- theta(x,...)
    a <- c()
    for (i in 1:n) {
      a <- append(a, theta(x[i, 1], x[i, 2]))
    }
    # Estimated total thus obtained from the initial sample
    thetahat <- sum(a/p)
    
    nboot <- length(bootsam)/2
    # bootsam<- matrix(sample(x,size=n*nboot,replace=TRUE),nrow=nboot)

    # thetastar <- apply(bootsam,1,theta,...)
    thetastar <- c()
    for (c in 1:B) {
      a <- c()
      for (i in 1:n) {
        a <- append(a, theta(bootsam[i, (2*c)-1], bootsam[i, 2*c]))
      }
      thetastar <- append(thetastar, sum(a/p))
    }
    thetastar <- sort(thetastar)

    z0 <- qnorm(sum(thetastar<thetahat)/nboot)
    
    u <- rep(0,n)
    for(i in 1:n){
        # u[i] <- theta(x[-i],...)
        x_i <- x[-i]
        a <- c()
        for (j in 1:n) {
          a <- append(a, theta(x_i[j, 1], x_i[j, 2]))
        }
        # Estimated total thus obtained from the initial sample
        u[i] <- sum(a/p)
    }
    uu <- mean(u)-u
    acc <- sum(uu*uu*uu)/(6*(sum(uu*uu))^1.5)
    
    zalpha <- qnorm(alpha)
    
    tt <- pnorm(z0+ (z0+zalpha)/(1-acc*(z0+zalpha)))
    
    confpoints <- quantile(x=thetastar,probs=tt,type=1)
    names(confpoints) <- NULL
    confpoints <- cbind(alpha,confpoints)
    dimnames(confpoints)[[2]] <- c("alpha","bca point")
    return(list(confpoints=confpoints, 
                z0=z0, 
                acc=acc, 
                u=u, 
                call=call))
}
```

```{r}
# bcanon(random_points,df_boot,circle_nb,alpha = .95)
# Produces an error
```

