---
title: "Bootstrap with a grid"
output:
  pdf_document: default
date: "2024-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl) # to read the initial file
library(magrittr) # for pipes
library(tibble) # for add_column
```

# Preliminaries

```{r}
# Importing the database with the artificial forest
trees <- read_excel("~/work/Sim_article2024/Data/artificial_forest_round.xls")
```

```{r}
# Functions to produce a local variable
source("~/work/Sim_article2024/Useful_functions/Circle.R")
```

```{r}
i <- sample(1:10, 1) # choice of the rank of the identifier we want
i
```

```{r}
# Dimension of a small square (length of one side of the square)
# We assume that c_dim is a divisor of 1000
c_dim <- 10
```

```{r}
# Function to sample at random following the grid
sampling_grid <- function(i,c_dim){
random_points <- data.frame(x = numeric(), y = numeric())

for (l in 0:((1000/c_dim)-1)) {
  if (l==0){
    x_init <- i*c_dim
  }else if ((3*l+i)*c_dim < (10)*c_dim){
    x_init <- (3*l+i)*c_dim
  }else{
    x_init <- (((3*l+i)*c_dim)%%(c_dim*10))
  }
  k <- 0
  while (x_init + 10*c_dim*k < 1000) {
    a <- runif(1, x_init + 10*c_dim*k, x_init + 10*c_dim*k + c_dim)
    b <- runif(1, l*c_dim, (l+1)*c_dim)
    random_points <- rbind(random_points, list(a,b))
    k <- k+1
  }
}
colnames(random_points) <- list("x", "y")
return(random_points)
}
```

# Monte Carlo alone

10 000 Monte Carlo iterations are appropriated.

```{r}
### Function to automate Monte Carlo method, to produce a variance

MonteCarlo <- function(B, f){
  # B: number of iterations for MC; 
  # f: function to consider (with 2 variables, x and y)
  
  est_MC <- c() # Vector containing all estimations
  for (b in 2:B) { # All in one "for" loop
    # Sampling over the whole territory
    df_grid <- sampling_grid(i,c_dim)
    # Variable of interest derived from the sample
    a <- mapply(f, df_grid$x, df_grid$y)
    n <- nrow(df_grid)
    p <- sum(rep((1/1000)*(1/1000), n)) # inclusion density
    est_MC <- append(est_MC, sum(a/p))
  }
  
  return(var(est_MC))
  # Monte-Carlo variance
}
```

# Bootstrap for each Monte Carlo iteration

1 000 Monte Carlo iterations and 400 bootstrap iterations for each one are appropriated.

```{r}
f_boot <- function(df_sample, B){
  # df_sample: original sample; 
  # B: number of bootstrap samples made thanks to df_sample
  
  df_boot <- tibble(.rows = (nrow(df_sample)-1))
  for (b in 1:B) {
    nb <- sample(1:nrow(df_sample), (nrow(df_sample)-1), replace = TRUE)
    # (n-1) points at random
    sample_b <- df_sample[nb,]
    df_boot <- df_boot %>% add_column(new_col = sample_b)
    colnames(df_boot)[b] <- paste("ech", b, sep = "")
  }
  return(do.call(data.frame, df_boot))
  # Return a data frame with B samples of 2 variables and of size n
}
```

```{r}
# Making of one estimation for each sample made by the bootstrap method
est_boot <- function(df, p){
  # df: dataframe with 3*B columns and n rows
  
  n <- nrow(df) + 1 # sample size of the initial sample
  nboot <- length(df)/3 # number of bootstrap samples
  vec_est <- c()
  for (c in 1:nboot) {
    vec_est <- append(vec_est, (n/(n-1))*sum(df[,3*c]/p))
    # (n/(n-1)) is the correction needed since we choose only (n-1) points
  }
  vec_est <- sort(vec_est)
  return(vec_est)
  # Vector with one estimation for each sample
}
```

```{r}
### Function to automate Monte Carlo + bootstrap method

MC_boot <- function(B1, B2, f){
  # B1: number of iterations for MC;
  # B2: number of iterations for bootstrap;
  # f: function to consider (2 arguments)
  
  var_est_boot <- c()
  for (b in 2:B1) {
    # One MC iteration at a time
    random_points <- sampling_grid(i,c_dim)
    random_points$var <- mapply(f, random_points[, 1], random_points[, 2])
    n <- nrow(random_points)
    p <- sum(rep((1/1000)*(1/1000), n))
    a <- sum(random_points$var/p)
    
    # Bootstrap iterations
    df_boot <- f_boot(random_points, B2)
    est_boot_val <- est_boot(df_boot, p)
    var_est_boot <- append(var_est_boot, var(est_boot_val))
  }
  return(mean(var_est_boot))
  # Mean of the bootstrap variance
}
```

# First example: number of trees

```{r}
start.time <- Sys.time()

res1_nb <- MonteCarlo(10000, circle_nb)
# Just one circle to begin with

end.time <- Sys.time()
time.taken <- end.time - start.time

time.taken
```

```{r}
cat("Monte Carlo variance:", res1_nb)
```

```{r}
start.time <- Sys.time()

res2_nb <- MC_boot(B1 = 1000, B2 = 400, f = circle_nb)
# Just one circle to begin with

end.time <- Sys.time()
time.taken <- end.time - start.time

time.taken
```

```{r}
cat("Mean of the variance of bootstrap samples:", res2_nb)
```

```{r}
cat("We get a difference of: ", 100*(max(res1_nb,res2_nb)-min(res1_nb,res2_nb))/min(res1_nb,res2_nb), "%", sep = "")
```

# Second example: volume of the forest

```{r}
start.time <- Sys.time()

res1_vol <- MonteCarlo(10000, circle_vol)
# Just one circle to begin with

end.time <- Sys.time()
time.taken <- end.time - start.time

time.taken
```

```{r}
cat("Monte Carlo variance:", res1_vol)
```

```{r}
start.time <- Sys.time()

res2_vol <- MC_boot(B1 = 1000, B2 = 400, f = circle_vol)
# Just one circle to begin with

end.time <- Sys.time()
time.taken <- end.time - start.time

time.taken
```

```{r}
cat("Mean of the variance of bootstrap samples:", res2_vol)
```

```{r}
cat("We get a difference of: ", 100*(max(res1_vol,res2_vol)-min(res1_vol,res2_vol))/min(res1_vol,res2_vol), "%", sep = "")
```
