---
title: "Test map France"
output: pdf_document
date: "2024-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("ggplot2")
install.packages("sf")
install.packages("ggspatial")
```

```{r}
library(ggplot2)
library(sf)
library(ggspatial)
```

```{r}
install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
library(rnaturalearth)
library(rnaturalearthdata)

# Get the map data for metropolitan France
france <- ne_countries(scale = "medium", country = "France", returnclass = "sf")
# france <- ne_states(country = "France", returnclass = "sf") %>%
#   filter(!name %in% c("Guyane", "Martinique", "Guadeloupe", "Réunion", "Mayotte"))  # Exclude overseas regions
```

```{r}
# NB: map doesn't go along with ggplot 

# library(maps)
# data(franceMapEnv)
```

```{r}
# Create a data frame with the coordinates and colors
# grid_data <- expand.grid(x = 1:30, y = 1:30)  # 10x10 grid
# grid_data$color <- "white"  # Default color for all squares

# (10--5)*2 = 30
# (51.5-41)*2 = 21

# Function to sample at random following the grid
sampling_grid <- function(i){
  cells_x <- c()
  cells_y <- c()
  
  for (l in 0:20) {
    if (l==0){
      x_init <- i
    }else if ((3*l+i) < 10){
      x_init <- (3*l+i)
    }else{
      x_init <- (((3*l+i))%%(10))
    }
    k <- 0
    while (x_init + 10*k < 30) {
      a <- x_init + 10*k
      b <- l
      cells_x <- append(cells_x, a)
      # print(a)
      cells_y <- append(cells_y, b)
      # print(b)
      k <- k+1
    }
  }
  return(data.frame(x = cells_x, y = cells_y))
}

test <- sampling_grid(3)
```

```{r}
# Define grid parameters
xmin <- -5   # Westernmost longitude
xmax <- 10   # Easternmost longitude
ymin <- 41   # Southernmost latitude
ymax <- 51.5   # Northernmost latitude
grid_size <- 0.5  # Grid size in degrees

# Create a grid
grid <- expand.grid(
  x = seq(xmin, xmax, by = grid_size),
  y = seq(ymin, ymax, by = grid_size)
)

# Convert the grid to an sf object
grid_sf <- st_as_sf(grid, coords = c("x", "y"), crs = 4326)

# Convert grid points to grid cells (polygons)
grid_sf <- st_make_grid(grid_sf, cellsize = c(grid_size, grid_size))

# Highlight specific cells
highlighted_cells <- grid_sf[test$x + (test$y)*30, ]  # Example: highlight specific cells
highlighted_cells <- st_sf(geometry = highlighted_cells, color = "red")  # Assign color

# Combine highlighted and non-highlighted cells
grid_sf <- st_sf(geometry = grid_sf, color = "white")
grid_sf$color[which(grid_sf$geometry %in% highlighted_cells$geometry)] <- highlighted_cells$color
```

```{r}
### First step: all chosen small squares in the grid

# Plot the map
ggplot() +
  geom_sf(data = france, fill = "lightblue") +
  geom_sf(data = grid_sf, aes(fill = color), color = "black", alpha = 0.4) +
  scale_fill_identity() +  # Use the colors defined in the grid_sf object
  coord_sf(xlim = c(xmin, xmax), ylim = c(ymin, ymax)) +
  theme_minimal() +
  ggtitle("Firs-stage sampling: sampling of cells within a grid") 
# +
  # annotation_scale(location = "bl") + # location = NULL
  # annotation_north_arrow(location = "bl")
```

```{r}
# Intersect grid with the map of France
intersected <- st_intersection(grid_sf, france)

# Create a new column to determine land or water (or other features)
# Here, we'll simply mark if a grid cell intersects with land (France)
grid_sf$color2 <- ifelse(st_intersects(grid_sf, france, sparse = FALSE), "green", "blue")
```

```{r}
grid_sf$color3 <- ifelse((grid_sf$color2 == "green") & (grid_sf$color == "red"), "orange", "white")
```

```{r}
### Second step: all chosen small squares that have at least a land part 

# Plot the map with color-coded grid cells
ggplot() +
  geom_sf(data = france, fill = "lightblue") +
  geom_sf(data = grid_sf, aes(fill = color3), color = "black", alpha = 0.4) +
  scale_fill_identity() +  # Use the colors defined in the grid_sf object
  coord_sf(xlim = c(xmin, xmax), ylim = c(ymin, ymax)) +
  theme_minimal() 
# +
  # ggtitle("")
```


