---
title: "Counting trees with a grid"
output: pdf_document
date: "2024-07-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl) # to read the initial file
library(magrittr) # for pipes
library(tibble) # for add_column
```

# Preliminaries

```{r}
# Importing the database with the artificial forest
trees <- read_excel("~/work/Sim_article2024/Data/artificial_forest_round.xls")
```

```{r}
# Functions to produce a local variable
source("~/work/Sim_article2024/Useful_functions/Circle.R")
```

# Creating a sample with a grid

```{r}
### Randomizing the positions of the numbers (from 1 to 10) 
# used to identify small squares in the grid
random10 <- sample(1:10)
rank_nb <- sample(1:10, 1) # choice of the rank of the identifier we want
nb <- random10[rank_nb] # the identifier thus chosen
```

```{r}
# Dimension of a small square (length of one side of the square)
# We assume that c_dim is a divisor of 1000
c_dim <- 10
```

## Plotting regular points to make sure it works

```{r}
# We want to target approximately one tenth of the area, 
# in order to reproduce figure 2.a. page 6 of Trinh et alii (2024)
# For this step, we choose regular points
regular_points <- data.frame(x = numeric(), y = numeric())

i <- rank_nb

for (l in 0:((1000/c_dim)-1)) {
  if (l==0){
    x_init <- i*c_dim
  }else if ((3*l+i)*c_dim < (10)*c_dim){
    x_init <- (3*l+i)*c_dim
  }else{
    x_init <- (((3*l+i)*c_dim)%%(c_dim*10))
  }
  k <- 0
  while (x_init + 10*c_dim*k < 1000) {
    # (a,b) is the center of each small square
    a <- ((x_init + 10*c_dim*k)+(x_init + 10*c_dim*k + c_dim))/2
    b <- ((l*c_dim)+(l+1)*c_dim)/2
    regular_points <- rbind(regular_points, list(a,b))
    k <- k+1
  }
}
colnames(regular_points) <- list("x", "y")
```

```{r}
plot(x = regular_points$x, y = regular_points$y, main = "Regular points", panel.first=grid())
```

```{r}
plot(x = regular_points$x, y = regular_points$y, main = "Regular points", panel.first=grid(), xlim = c(0, 1000), ylim = c(0, 160))
```

## Sampling in each small square of the grid

```{r}
# Now, we sample at random following the grid
random_points <- data.frame(x = numeric(), y = numeric())

i <- rank_nb

for (l in 0:((1000/c_dim)-1)) {
  if (l==0){
    x_init <- i*c_dim
  }else if ((3*l+i)*c_dim < (10)*c_dim){
    x_init <- (3*l+i)*c_dim
  }else{
    x_init <- (((3*l+i)*c_dim)%%(c_dim*10))
  }
  k <- 0
  while (x_init + 10*c_dim*k < 1000) {
    a <- runif(1, x_init + 10*c_dim*k, x_init + 10*c_dim*k + c_dim)
    b <- runif(1, l*c_dim, (l+1)*c_dim)
    random_points <- rbind(random_points, list(a,b))
    k <- k+1
  }
}
colnames(random_points) <- list("x", "y")
```

```{r}
plot(x = random_points$x, y = random_points$y, main = "Random points", panel.first=grid())
```

```{r}
plot(x = random_points$x, y = random_points$y, main = "Random points", panel.first=grid(), xlim = c(0, 1000), ylim = c(0, 160))
```

```{r}
rm(a,b,i,l,x_init,k)
```

```{r}
### Values available after sampling

# Sample size
n <- nrow(random_points)

# Marginal density: density of the uniform distribution over 1:1000
# Which leads us to the inclusion density function
p <- sum(rep((1/1000)*(1/1000), n))
```

# Bootstrap

## Creating other samples based on the previous one

```{r}
# Number of bootstrap samples
B <- 500
```

```{r}
f_boot <- function(df_sample, B){
  # df_sample: original sample; B: number of bootstrap samples made thanks to df_sample
  
  df_boot <- tibble(.rows = nrow(df_sample))
  for (b in 1:B) {
    nb <- sample(1:nrow(df_sample), nrow(df_sample), replace = TRUE)
    sample_b <- df_sample[nb,]
    df_boot <- df_boot %>% add_column(new_col = sample_b)
    colnames(df_boot)[b] <- paste("ech", b, sep = "")
  }
  return(do.call(data.frame, df_boot))
  # Return a data frame with B samples of 2 variables and of size n
}
```

```{r}
# Making of bootstrap samples
df_boot <- f_boot(random_points, B)
```

## Estimations and confidence intervals based on the bootstrap samples with three circles

```{r}
ci_boot <- function(df_init, df_boot){
  # df: dataframe with 2*B columns and n rows
  
  ## 1st step: 1 estimation for each sample
  est_boot <- c()
  for (c in 1:B) {
    a <- mapply(circle3_nb, df_boot[, (2*c)-1], df_boot[, 2*c], MoreArgs = list(15, 9, 6))
    est_boot <- append(est_boot, sum(a/p))
  }
  est_boot <- sort(est_boot)
  
  ## 2nd step: percentile CI
  lim_inf <- est_boot[floor(B*2.5/100)]
  lim_sup <- est_boot[B - floor(B*2.5/100)]
  cat("Un intervalle de confiance à 95% par la méthode des percentiles est : 
      [", lim_inf, ";", lim_sup, "]\n" )
  
  ## 3rd step: reverse percentile CI
  # Target: the initial sample alone
  a <- mapply(circle3_nb, df_init[, 1], df_init[, 2], MoreArgs = list(15, 9, 6))
  est_init <- sum(a/p) # Estimated total thus obtained from the initial sample
  cat("Un intervalle de confiance à 95% par la méthode des reverse percentiles est : 
      [", est_init*2 - lim_sup, ";", est_init*2 - lim_inf, "]\n" )
  return(c(est_init,lim_inf,lim_sup))
}
```

```{r}
start.time <- Sys.time()

res <- ci_boot(random_points,df_boot)

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

# Ex:
# Un intervalle de confiance à 95% par la méthode des percentiles est : 
#      [ 25979.59 ; 32051.31 ]
# Un intervalle de confiance à 95% par la méthode des reverse percentiles est :
# [ 26421.35 ; 32493.07 ]

# Ex:
# Un intervalle de confiance à 95% par la méthode des percentiles est : 
#       [ 25979.59 ; 32051.31 ]
# Un intervalle de confiance à 95% par la méthode des reverse percentiles est : 
#       [ 26421.35 ; 32493.07 ]
# Time difference of 12.57769 mins
```

## The same thing with the total volume

```{r}
ci_boot_vol <- function(df_init, df_boot){
  # df: dataframe with 2*B columns and n rows
  
  ## 1st step: 1 estimation for each sample
  est_boot <- c()
  for (c in 1:B) {
    a <- mapply(circle3_vol, df_boot[, (2*c)-1], df_boot[, 2*c], MoreArgs = list(15, 9, 6))
    est_boot <- append(est_boot, sum(a/p))
  }
  est_boot <- sort(est_boot)
  
  ## 2nd step: percentile CI
  lim_inf <- est_boot[floor(B*2.5/100)]
  lim_sup <- est_boot[B - floor(B*2.5/100)]
  cat("Un intervalle de confiance à 95% par la méthode des percentiles est : 
      [", lim_inf, ";", lim_sup, "]\n" )
  
  ## 3rd step: reverse percentile CI
  # Target: the initial sample alone
  a <- mapply(circle3_vol, df_init[, 1], df_init[, 2], MoreArgs = list(15, 9, 6))
  est_init <- sum(a/p) # Estimated total thus obtained from the initial sample
  cat("Un intervalle de confiance à 95% par la méthode des reverse percentiles est : 
      [", est_init*2 - lim_sup, ";", est_init*2 - lim_inf, "]\n" )
  return(c(est_init,lim_inf,lim_sup))
}
```

```{r}
start.time <- Sys.time()

res <- ci_boot_vol(random_points,df_boot)

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```











