---
title: "Trees in circles"
output: pdf_document
date: "2024-06-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminaries

```{r}
# Importing the database with the artificial forest
trees <- read_excel("~/work/Sim_article2024/Data/artificial_forest_round.xls")
```

```{r}
# Sample size
n <- 100
```

```{r}
# Radius
R <- 10
```

```{r}
# Marginal density: density of the uniform distribution over 1:1000
# Which leads us to the inclusion density function
# p <- sum(rep((1/1000)*(1/1000), n)) # :(
# p

# I would say that pi changes: area of each circle over total area for each marginal
# p <- sum(rep((1/1000)*(1/1000)*(R^2)*pi, n)) # :(

# p <- sum(rep((1/1000)*(1/1000)*((R^2)*pi)/2, n))
```

# With no cell

## Creating one sample

```{r}
# Dataframe containing all coordinates of n randomly chosen points
random_points <- data.frame(x = rep(0, n), y = rep(0, n))
```

```{r}
# Uniform sampling over the whole territory
random_points$x <- runif(n, 0, 1000)
random_points$y <- runif(n, 0, 1000)
```

```{r}
# Function to check if a point is inside the circle
is_point_in_circle <- function(x, y, h, k, R) {
  # Calculate the squared distance between the point and the center of the circle
  squared_distance <- (x - h)^2 + (y - k)^2
  # Check if the squared distance is less than or equal to the squared radius
  return(as.numeric(squared_distance <= R^2))
}
```

```{r}
trees_in <- data.frame(useless = rep(0,30942))
col_names <- c()
for (point in 1:n) {
  new_col <- paste("point", point, sep = "")
  a <- random_points[point,]$x
  b <- random_points[point,]$y
  val <- is_point_in_circle(a, b, trees$x, trees$y, R)*point
  trees_in <- trees_in %>% add_column(new_col = val)
  col_names <- append(col_names, new_col)
}
trees_in[1] <- NULL
colnames(trees_in) <- col_names
```

```{r}
rm(a,b,val,col_names)
```

```{r}
nb_trees <- c()

for (placette in 1:n) {
  nb_trees <- append(nb_trees, sum(trees_in[trees_in$point74 != 0,]))
}

sum((nb_trees)/p)
# 28737017 # TOO MUCH, p is (probably) wrong
# 9.028e+09 # if p unchanged i.e. sum(rep((1/1000)*(1/1000), n))
# 57474033 # TOO MUCH, p is (probably) wrong if sum(rep((1/1000)*(1/1000)*((R^2)*pi)/2, n))
```

```{r}
trees$Is_in_circle <- is_point_in_circle(500, 500, trees$x, trees$y, 100)
unique(trees$Is_in_circle)
```

```{r}
# The sample thus obtained
trees[trees$Is_in_circle == TRUE,]
```

```{r}
total_trees <- nrow(trees[trees$Is_in_circle == TRUE,])
```

```{r}
trees$Is_in_circle <- is_point_in_circle(580.869189, 797.312061, trees$x, trees$y, 100)
unique(trees$Is_in_circle)
```

```{r}

```

