---
title: "With three circles"
output: html_document
date: "2024-07-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
circle3_nb <- function(x1, x2, R1, R2, R3){
  # 2 coordinates (x1, x2) and 3 radii (R1 > R2 > R3)
  
  # Preliminary: inclusion area
  source("~/work/Sim_article2024/Useful_functions/Inc_area.R")
  
  list_trees <- trees[(x1 - trees$x)^2 + (x2 - trees$y)^2 <= R1^2,] # List with all trees inside the biggest circle
  
  list_trees1 <- list_trees[(pi*list_trees$d130 > 117.5),] # List with the biggest trees
  list_trees2 <- list_trees[(pi*list_trees$d130 < 117.5) & (pi*list_trees$d130 > 70.5) & ((x1 - list_trees$x)^2 + (x2 - list_trees$y)^2 <= R2^2),] # medium trees
  list_trees3 <- list_trees[(pi*list_trees$d130 < 70.5) & (pi*list_trees$d130 > 23.5) & ((x1 - list_trees$x)^2 + (x2 - list_trees$y)^2 <= R3^2),] # smallest trees
  
  local_var1 <- sum(length(list_trees1)/inc_area(c(x1, x2),0,0,1000,1000,R1)) # Local variable for the biggest circle and the biggest trees
  local_var2 <- sum(length(list_trees2)/inc_area(c(x1, x2),0,0,1000,1000,R2)) # Local variable for the medium circle and the medium trees
  local_var3 <- sum(length(list_trees3)/inc_area(c(x1, x2),0,0,1000,1000,R3)) # Local variable for the smallest circle and the smallest trees
  local_var <- (local_var1 + local_var2 + local_var3) # Addition of the previous local variables
  # /3 # Doesn't work
  return(local_var)
  # local_var: local variable based on the number of trees
}
```

```{r}
circle3_nb(500, 500, 15, 9, 6)
# 0.08511842 e.g.
```

```{r}

```

```{r}

```

```{r}

```

