---
title: "Test"
output:
  pdf_document: default
  html_document: default
date: "2024-06-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vec_test <- c(0,1,2)
f <- function(data, indice){
  d <- data[indice]
  return(c((d[1]+d[2]+d[3])/3))
}
boot(data=vec_test, statistic=f, R=10)
```

# Variance théorique

```{r}
for (k in 1:nrow(trees)) {
  for (i in 1:k) {
    
  }
  sum_i <- sum()
}
```

# MC_boot

## Tests

```{r}
start.time <- Sys.time()

MC_boot(n = 100, B1 = 1000, B2 = 200, f = circle3_nb)
# Way too long
```

```{r}
start.time <- Sys.time()

res <- MC_boot(n = 100, B1 = 500, B2 = 100, f = circle3_nb)

end.time <- Sys.time()
time.taken1 <- end.time - start.time

time.taken1
# Way too long
```

```{r}
start.time <- Sys.time()

res <- MC_boot(n = 50, B1 = 10, B2 = 5, f = circle3_nb)

end.time <- Sys.time()
time.taken2 <- end.time - start.time

time.taken2
# Time difference of 5.522393 secs
# 31471.63 78177624.15 53692218.51
```

```{r}
start.time <- Sys.time()

res <- MC_boot(n = 100, B1 = 100, B2 = 50, f = circle3_nb)

end.time <- Sys.time()
time.taken2 <- end.time - start.time

time.taken2
# Time difference of 5.522393 secs
# 31471.63 78177624.15 53692218.51
```

# Volume

```{r}
# Total volume of trees
a <- mapply(circle3_vol, random_points[, 1], random_points[, 2], MoreArgs = list(15, 9, 6))
est_init_vol <- sum(a/p)
rm(a)
cat("Volume of the forest:", sum(trees$v), "\nEstimation of the volume of the forest:", est_init_vol)
```

# Draft from adapt_boot

```{r}
plot(x = random_points[, 1], y = random_points$var, xlab = "x", main = "Points as a function of x", las = 1)
```

```{r}
plot(x = random_points[, 2], y = random_points$var, xlab = "y", main = "Points as a function of y", las = 1)
```

# Plot concentric circles

```{r}
# Set up the plotting area
plot(1, type="n", xlab="", ylab="", xlim=c(-16, 16), ylim=c(-16, 16), asp=1)

# Draw three concentric circles with increasing radius
symbols(rep(0, 3), rep(0, 3), circles=c(6, 9, 15), inches=FALSE, add=TRUE, fg = rep("navyblue", 2))

# Medium trees
symbols(c(10, -13), c(-5, 3), circles=c(2.5, 3.6), inches=FALSE, add=TRUE, fg = rep("forestgreen", 2))

# Little trees (between 4 and 12 grosso modo)
symbols(c(10, -13), c(-5, 3), circles=c(4, 6), inches=FALSE, add=TRUE, fg = rep("green", 2))

# Centers of trees
points(c(10, -13), c(-5, 3), pch=19, col="black", cex=0.2)

# Add axis lines for reference (optional)
abline(h=0, v=0, col="gray")

```

```{r}
# Set up the plotting area
plot(1, type="n", xlab="", ylab="", xlim=c(-16, 16), ylim=c(-10, 10), asp=1)

# Draw three concentric circles with increasing radius
symbols(rep(0, 2), rep(0, 2), circles=c(6, 9), inches=FALSE, add=TRUE, fg = rep("navyblue", 2))

# Medium trees
symbols(c(8, -4), c(2, 3), circles=c(2.5, 3.6), inches=FALSE, add=TRUE, fg = rep("forestgreen", 2))

# Little trees (between 4 and 12 grosso modo)
symbols(c(7, -3), c(-5, 3), circles=c(4, 6), inches=FALSE, add=TRUE, fg = rep("green", 2))

# Centers of trees
points(c(10, -13), c(-5, 3), pch=19, col="black", cex=0.2)

# Add axis lines for reference (optional)
abline(h=0, v=0, col="gray")

```

```{r}
# Set up the plotting area
plot(1, type="n", xlab="", ylab="", xlim=c(-20, 20), ylim=c(-20, 20), asp=1)

# Draw three concentric circles with increasing radius
symbols(0, 0, circles=10, inches=FALSE, add=TRUE, fg = "navyblue")

# Bad trees
symbols(c(15, -5), c(2, 10.5), circles=c(2.5, 3.7), inches=FALSE, add=TRUE, fg = rep("grey", 2))

# good trees 
symbols(c(7, 2,-4), c(-5, 3, -5), circles=c(4, 3, 2), inches=FALSE, add=TRUE, fg = rep("forestgreen", 2))

# Centers of trees
points(c(15, -5, 7, 2, -4), c(2, 10.5, -5, 3, -5), pch=as.character(1:5), col="black", cex=0.7) # pch=19

# Add axis lines for reference (optional)
# abline(h=0, v=0, col="gray")

```

```{r}
# Set up the plotting area
my_plot <- plot(1, type="n", xlab="", ylab="", xlim=c(-20, 20), ylim=c(-20, 20), asp=1, xaxt="n", yaxt="n")+
  
  # axis.ticks.x = element_blank(),
  # Draw three concentric circles with increasing radius
  symbols(0, 0, circles=10, inches=FALSE, add=TRUE, fg = "navyblue")+
  
  # Bad trees
  symbols(c(15, -5, -11), c(2, 10.5, -11), circles=c(2.5, 3.7, 2), inches=FALSE, add=TRUE, fg = rep("grey", 2))+
  
  # good trees 
  symbols(c(7, 4,-4), c(-5, 3.5, -5), circles=c(4, 3.5, 2), inches=FALSE, add=TRUE, fg = rep("forestgreen", 2))+
  
  # Centers of trees
  points(c(15, -5, 7, 4, -4, -11), c(2, 10.5, -5, 3.5, -5, -11), pch=as.character(1:6), col="black", cex=0.7) # pch=19

# Sampled point
points(0, 0, pch=19, col="red", cex=0.7) # pch=19
points(-0.2, -0.72, pch="S", col="red", cex=0.7)

# theme(axis.text.x = element_blank(), axis.text.y = element_blank())
#theme(axis.ticks.x = element_blank(), axis.ticks.y = element_blank())
```

